version: 0.2

phases:
  build:
    base-directory: /tmp/working/bitester
    commands:
      - hugo -D 
  post_build:
    commands:
      - aws s3 sync ./public s3://$OUTPUT_BUCKET
# create an archive artifact
artifacts:
  name: bitester-blog_$(date +%Y-%m-%d) 
  files:
    - '**/*'
